apiVersion: v1
kind: Service
metadata:
  name: parenting-assistant-service
spec:
  selector:
    app: parenting-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
